
on: [push]

name: azureARMDeploy

jobs:

    deploy:
      runs-on: ubuntu-latest
      steps:

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Checkoout source code
        uses: actions/checkout@v2

      - name: Deploy ARM Template
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az deployment group create \
            --name StorageAccountDeployment \
            --resource-group a-dev-apprg \
            --template-file armtemplates/storageaccount.json